[build]
  functions = "netlify-functions"
  command = "bash ./netlify-scripts/build.sh"

[[plugins]]
  package = "./netlify-plugins/python-virtualenv"

[[plugins]]
  package = "@netlify/plugin-functions-install"

[[plugins]]
  package = "@netlify/plugin-nextjs"
